### ISSUE TITLE
```yaml

### ISSUE THREAD

**Issue by akiragg** [zhaohmng-outlook-com/21-#91]
```yaml
{
  "base-paths": "src/*/py"
  "paths": "src/*/py"
  "": {
    "base-paths": "src/*/py"
    "paths": "src/*/py"
  }
  "build": {
    "paths": "src/*/py"
    "symlink-install": true
    "cmake-args": "-DCMAKE_BUILD_TYPE=Debug"
  }
  "list": {
    "base-paths": "src/*/py"
    "paths": "src/*/py"
  }
}
```

None of the "paths" or "base-paths" verbs are respected by Colcon.  
`colcon list --paths-only --paths src/* src/*/py` shows expected output  
`colcon list --paths-only` does not

__最初由 @HighPriest 在 https://github.com/colcon/colcon-core/issues/438 发布__
